//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace motorizados_servicio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class motorizado
    {
        public int id { get; set; }
        public decimal latitud { get; set; }
        public decimal longitud { get; set; }
        public string url { get; set; }
    }
}
